/*
 * Copyright 2024-2026 SOFT-POL
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package eu.softpol.lib.jgpio.internal;

import static eu.softpol.lib.jgpio.internal.LibDiscovery.PathDiscoveryResult.LIB_FOUND;
import static eu.softpol.lib.jgpio.internal.LibDiscovery.PathDiscoveryResult.LIB_NOT_FOUND;

import eu.softpol.lib.jgpio.JgpioException;
import java.io.File;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.lang.foreign.Arena;
import java.lang.foreign.SymbolLookup;
import java.lang.invoke.MethodHandles;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.stream.Collectors;

public class LibDiscovery {

  private static final Logger logger = System.getLogger(LibDiscovery.class.getName());

  private LibDiscovery() {
  }

  /// Detects the version of the installed libgpiod library.
  ///
  /// @return the libgpiod version
  /// @throws JgpioException if the library cannot be opened or its version is not supported
  public static LibgpiodVersion detectVersion() {
    return detectVersion("gpiod");
  }

  /// Detects the libgpiod version by the symbols exported by the library.
  ///
  /// @param libName library name
  /// @return the libgpiod version
  /// @throws JgpioException if the library cannot be opened or its version is not supported
  static LibgpiodVersion detectVersion(String libName) {
    var nativeLibName = System.mapLibraryName(libName);
    try (var arena = Arena.ofConfined()) {
      var lookup = SymbolLookup.libraryLookup(nativeLibName, arena);
      if (lookup.find("gpiod_api_version").isPresent()) { // 2.x only
        logger.log(Level.DEBUG, "Detected libgpiod v2");
        return LibgpiodVersion.V2;
      }
      if (lookup.find("gpiod_version_string").isPresent()) { // 1.x only
        logger.log(Level.DEBUG, "Detected libgpiod v1");
        return LibgpiodVersion.V1;
      }
      throw new JgpioException("Unsupported " + libName + " library version, `" + nativeLibName
                               + "` exports neither `gpiod_api_version` nor `gpiod_version_string`");
    } catch (IllegalArgumentException ex) {
      throw cannotOpenLibrary(libName, ex);
    }
  }

  /// Try to load the library, in case of problems print detailed information about the context of
  /// the problem
  ///
  /// @param clazz   class generated by jextract
  /// @param libName library name
  public static void tryToInitLibrary(Class<?> clazz, String libName) {
    try {
      // triggering class initialization
      MethodHandles.lookup().ensureInitialized(clazz);
    } catch (ExceptionInInitializerError | IllegalAccessException ex) {
      throw cannotOpenLibrary(libName, ex);
    }
  }

  /// Prints detailed information about the context of the problem with opening the library
  ///
  /// @param libName library name
  /// @param cause   the reason the library cannot be opened
  /// @return the exception to throw
  private static JgpioException cannotOpenLibrary(String libName, Throwable cause) {
    var nativeLibName = System.mapLibraryName(libName);
    var libAnalysis = LibDiscovery.analyzeLibraryPath(nativeLibName);

    logger.log(Level.ERROR, "Cannot open {0} library.", libName);
    logger.log(Level.ERROR, """
            The JGPIO lib checked for `{0}` file in the `java.library.path` and these are the results:
            {1}
            """,
        nativeLibName,
        libAnalysis.entrySet().stream()
            .map(kv -> " - " + kv.getKey() + " - " + switch (kv.getValue()) {
              case LIB_NOT_FOUND -> "not found";
              case LIB_FOUND -> "**LIB FOUND**";
            })
            .collect(Collectors.joining("\n"))
    );

    var foundPaths = libAnalysis.entrySet().stream()
        .filter(kv -> kv.getValue() == LIB_FOUND)
        .map(Entry::getKey)
        .toList();
    if (!foundPaths.isEmpty()) {
      logger.log(Level.ERROR, """
              Looks like {0} file has been found, but cannot be loaded.
              Your system may require setting the lib directory in the `LD_LIBRARY_PATH` environment variable.
              Please check `dlopen` manual for more details.
              """,
          nativeLibName);
    }
    return new JgpioException("Cannot open " + libName + " library", cause);
  }

  /// Check if library located in the java library path
  ///
  /// @param nativeLibName library name
  /// @return map of paths with search result
  private static Map<String, PathDiscoveryResult> analyzeLibraryPath(String nativeLibName) {
    var libPath = Objects.requireNonNullElse(System.getProperty("java.library.path"), "");

    var result = new HashMap<String, PathDiscoveryResult>();
    for (var path : libPath.split(File.pathSeparator)) {
      result.put(
          path,
          Files.exists(Path.of(path, nativeLibName)) ? LIB_FOUND : LIB_NOT_FOUND
      );
    }
    return Map.copyOf(result);
  }

  enum PathDiscoveryResult {
    LIB_FOUND,
    LIB_NOT_FOUND;
  }

  public enum LibgpiodVersion {
    V1,
    V2;
  }
}
