name: Prepare SNAPSHOT

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Next version (-SNAPSHOT will be added automatically)'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    - name: Set release version
      run: |
        mvn -B -ntp -f jgpio/pom.xml versions:set -DnewVersion=${{ github.event.inputs.version }}-SNAPSHOT -DgenerateBackupPoms=false
        mvn -B -ntp -f jgpio-it/pom.xml versions:set -DnewVersion=${{ github.event.inputs.version }}-SNAPSHOT -DgenerateBackupPoms=false

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        title: 'Prepare ${{ github.event.inputs.version }}-SNAPSHOT'
        body: 'Automated preparation of ${{ github.event.inputs.version }}-SNAPSHOT'
        commit-message: 'Set version to ${{ github.event.inputs.version }}-SNAPSHOT'
        branch: 'snapshot-${{ github.event.inputs.version }}-SNAPSHOT'
